name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  publish:
    name: Publish to npm
    environment: NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: npm
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        if: ${{ secrets.NPM_TOKEN != '' }}
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Skip publish (missing token)
        if: ${{ secrets.NPM_TOKEN == '' }}
        run: echo "NPM_TOKEN not set, skipping publish. Configure repository secret to enable publishing."
